name: 'Publish to Heroku' #set whatevername you want to your github job
on:
  push:
    branches: [main, master]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        uses: gonuit/heroku-docker-deploy@v1.3.3 # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }} # you aplication name
          dockerfile_directory: ./ # set the path to the folder wher the Dokerfile is located
          dockerfile_name: Dockerfile
          docker_options: --build-arg GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}
